stages:
    - deploy

cache:
  paths:
  key: "$CI_JOB_NAME"

deploy_job:
  stage: deploy
  image: docker:stable
  variables:
    PLAYWD: 172-18-0-106-bqa46vtim9m000fjjuig
  script:
    - apk add --no-cache openssh-client py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
    - export DOCKER_HOST=tcp://$PLAYWD.direct.labs.play-with-docker.com:2375
    - docker-compose down
    - docker-compose up -d -f ./karya/docker-compose.yml
  environment:
    name: staging
    url: http://$PLAYWD-8080.direct.labs.play-with-docker.com
