stages:
    - package
    - deploy

cache:
  paths:
  key: "$CI_JOB_NAME"

package_job:
  stage: package
  services:
    - docker:stable-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  script:
    - apk add --no-cache docker
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t moussi.gl/node:1.0 -f Dockerfile.node .
    - docker build -t moussi.gl/karya:1.0 .
    - docker pull mongo:4.2.5-bionic -t moussi.gl/mongo:1.0
    - docker push

# deploy_job:
#   stage: deploy
#   image: docker:stable
#   variables:
#     PLAYWD: 172-18-0-106-bqa46vtim9m000fjjuig
#   script:
#     - apk add --no-cache openssh-client py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
#     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#     - pip install docker-compose
#     - export DOCKER_HOST=tcp://$PLAYWD.direct.labs.play-with-docker.com:2375
#     - docker-compose up -d
#   environment:
#     name: staging
#     url: http://$PLAYWD-8080.direct.labs.play-with-docker.com
