sudo: required

services:
    - docker

before_install:
    - docker build -t moussi/karya -f Dockerfile.dev .

script:
    - docker run moussi/karya ng test -- --no-watch --no-progress

deploy:
    provider: elasticbeanstalk
    region: "eu-west-3"
    app: "karya"
    env: "Karya-env"
    bucket_name: "elasticbeanstalk-eu-west-3-427280325071"
    bucket_path: "karya"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
