"""empty message

Revision ID: df5178c76195
Revises:
Create Date: 2020-01-08 15:05:27.071400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df5178c76195'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('rental',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('street', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('shared', sa.Boolean(), nullable=True),
    sa.Column('daily_rate', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rental_category'), 'rental', ['category'], unique=True)
    op.create_index(op.f('ix_rental_city'), 'rental', ['city'], unique=True)
    op.create_index(op.f('ix_rental_description'), 'rental', ['description'], unique=True)
    op.create_index(op.f('ix_rental_image'), 'rental', ['image'], unique=True)
    op.create_index(op.f('ix_rental_street'), 'rental', ['street'], unique=True)
    op.create_index(op.f('ix_rental_title'), 'rental', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rental_title'), table_name='rental')
    op.drop_index(op.f('ix_rental_street'), table_name='rental')
    op.drop_index(op.f('ix_rental_image'), table_name='rental')
    op.drop_index(op.f('ix_rental_description'), table_name='rental')
    op.drop_index(op.f('ix_rental_city'), table_name='rental')
    op.drop_index(op.f('ix_rental_category'), table_name='rental')
    op.drop_table('rental')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
